export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const LOAD_RACES_SUCCESS = 'LOAD_RACES_SUCCESS';
export const LOAD_RACE_SUCCESS = 'LOAD_RACE_SUCCESS';
